device:
    gpu: 0
    n_workers: 0

seed: 10

task: od

model:
    arch: frcnn 
    version: coco
    path: torchvision 
    with_bn: False
   
data:
    dataset: carla
    version: carla 
    train_split: train
    val_split: val
    test_split: test
    img_rows: 800
    img_cols: 1333
    path: /path/to/carla-gear/dataset
    img_norm: True
    bgr: False
    bottom_crop: 0
    std_version: 


adv_patch:
    path: 
        resume: 
        out_dir: /path/to/exp/root
        save_patch: True
        exp_name: exp_name

    patch_opt:
      use_predicted_labels: False
      attack: attack_od
      optimizer:
        lr: 0.5
        name: adam #default
      loss:
        adv_loss:
            name: 'multi_scale_patch_composition'
            factor: 1
            mult_factor: [1.0, 1.0, 1.0, 1.0]     # loss_cls, loss_bbox, loss_obj, loss_rpn_bbox
        smoothness:
            name: 'smoothness_loss'
            args: None
            factor: 0.1
        NPS:
            name: 'NPS'
            args: '/data01/f.nesti/SemanticSegmentation/printable_colors.txt'
            factor: 0
              
      batch_size_val: 1
      batch_size_opt: 1
        
      num_opt_samples: 100
      opt_iters: 50

      batch_size: 1

      use_multiple_outputs: True    # Aux logits on/off

      log_iters: 10 # test_every
      test_log: 10 # test_every
      save_iters: 10   # save_every

      opt_validation_log1: True   # online_validation
        
      # EOT
      use_transformations: True

      use_rw_transformations: True
    

    num_patches: 1
        

    attr:
        width : 300 # pixels
        height : 150
        world_width: 7.4
        offset: [0, 3.6, 1.85] # in meters
        
        # Old settings 
        pixel_width: 0.08
        height_offset: 1
        rescale: 2
        x_offset: 1
        block_width: 5 # width and height must be divisible by this number. The exceeding parts of the patch will not be projected.
        pos_x: 500
        pos_y: 450
        target_label:  
        attacked_label: 
        bbox: #[458, 325, 150, 150]